// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQWnIeOWq2Z72mRfZ_fGChUpQq2UpI0UI',
    appId: '1:408425129985:web:e8d363cf0ac2411f487800',
    messagingSenderId: '408425129985',
    projectId: 'fluttapp-19dc2',
    authDomain: 'fluttapp-19dc2.firebaseapp.com',
    storageBucket: 'fluttapp-19dc2.appspot.com',
    measurementId: 'G-D2CCDWFH12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxezVKiW-VZNj8B6rleVHABODu0mNl7Hs',
    appId: '1:408425129985:android:847bf668da49c093487800',
    messagingSenderId: '408425129985',
    projectId: 'fluttapp-19dc2',
    storageBucket: 'fluttapp-19dc2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf-YB19DcyxlpFKLjTy32IHmjjONBWVAY',
    appId: '1:408425129985:ios:30a237d63a31f9e8487800',
    messagingSenderId: '408425129985',
    projectId: 'fluttapp-19dc2',
    storageBucket: 'fluttapp-19dc2.appspot.com',
    iosClientId: '408425129985-905q3jqlm2c3iel0kc0kqt5o10agh9fo.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf-YB19DcyxlpFKLjTy32IHmjjONBWVAY',
    appId: '1:408425129985:ios:fb41350c2a361588487800',
    messagingSenderId: '408425129985',
    projectId: 'fluttapp-19dc2',
    storageBucket: 'fluttapp-19dc2.appspot.com',
    iosClientId: '408425129985-odg8ivnrr06ta3ttlvce109jvkm62ppe.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttapp.RunnerTests',
  );
}
